# Generated by Django 4.0.5 on 2022-06-25 20:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direction',
            field=models.TextField(verbose_name=api.models.Direction),
        ),
    ]
