# Generated by Django 4.0.5 on 2022-06-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_directioninline_delete_directionforchoose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.direction'),
        ),
        migrations.DeleteModel(
            name='DirectionInLine',
        ),
    ]
