# Generated by Django 4.0.5 on 2022-06-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_doctor_direction_delete_directioninline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='experience',
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.CharField(max_length=128),
        ),
    ]
