# Generated by Django 4.0.5 on 2022-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_directiondir_alter_doctordir_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slag', models.CharField(max_length=128)),
                ('number_sort', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctordir',
            name='direction',
        ),
        migrations.DeleteModel(
            name='DirectionDir',
        ),
        migrations.DeleteModel(
            name='DoctorDir',
        ),
        migrations.AddField(
            model_name='doctor',
            name='directions',
            field=models.ManyToManyField(to='api.choose'),
        ),
    ]
