# Generated by Django 4.0.5 on 2022-06-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_choose_remove_doctordir_direction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choose',
            options={'verbose_name': 'Лікарfddа', 'verbose_name_plural': 'Лdfdfікарі'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='direction',
        ),
    ]
