# Generated by Django 4.0.5 on 2022-07-05 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_choose_alter_doctor_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='directions',
        ),
        migrations.AddField(
            model_name='doctor',
            name='direction',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='api.direction'),
        ),
    ]
