# Generated by Django 4.0.5 on 2022-07-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_doctor_directions_doctor_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='direction',
        ),
        migrations.AddField(
            model_name='doctor',
            name='directions',
            field=models.ManyToManyField(to='api.direction'),
        ),
    ]
